apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  labels:
    app: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}
  name: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}
    spec:
      imagePullSecrets:
      - name: harborsecret
      containers:
      - image: ghcr.io/liandj/hello-world:22
        name: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 4096m
            memory: 6Gi
          requests:
            cpu: 1024m
            memory: 1Gi       
        env: # 添加
        - name: TZ                       # 添加
          value: Asia/Shanghai
