name: CI/CD Pipeline

on:
  push:
    branches:
      - mac-test # 监听master分支的推送

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.run_number }}

      - name: Install sshpass
        run: |
          #sudo apt-get update && sudo apt-get install -y sshpass
          echo ${{ github.repository.deployments_url }}

      - name: Deploy to server
        env:
          SERVER_USER: ubuntu
          SERVER_IP: 43.160.206.35
          SERVER_PASSWD: ${{ secrets.UBUNTU_PASSWD }}
          GITHUB_PAT: ${{ secrets.LIAN_PAT }}
        run: |
          echo "hello world"

            # 启动新的容器
            sudo docker run -d -p 80:80 --name my-nginx-container ghcr.io/${{ github.repository }}:${{ github.run_number }}
          "
