name: CI/CD Pipeline

on:
  push:
    branches:
      - mac-test # 监听master分支的推送

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          echo ${{ github.repository }}

      - name: Deploy to server
        env:
          SERVER_USER: ubuntu
          SERVER_IP: 43.160.206.35
          SERVER_PASSWD: ${{ secrets.UBUNTU_PASSWD }}
          GITHUB_PAT: ${{ secrets.LIAN_PAT }}
        run: |
          who
          ls -la /tmp/
