name: CI/CD Pipeline

on:
  push:
    branches:
      - main # 监听main分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          SERVER_USER: ubuntu
          SERVER_IP: 43.160.206.35
          SERVER_PASSWD: ${{ secrets.UBUNTU_PASSWD }}
          GITHUB_PAT: ${{ secrets.LIAN_PAT }}
        run: |
          # 使用sshpass和密码登录到服务器并执行部署命令
          sshpass -p "$SERVER_PASSWD" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "
            # 登录到GitHub Container Registry
            echo $GITHUB_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

            # 拉取最新的镜像
            docker pull ghcr.io/${{ github.repository }}:latest

            # 停止并移除旧的容器（如果存在）
            docker stop my-nginx-container || true
            docker rm my-nginx-container || true

            # 启动新的容器
            docker run -d -p 80:80 --name my-nginx-container ghcr.io/${{ github.repository }}:latest
          "
