---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}-ingress
  namespace: {{NAMESPACE}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host:  {{NAMESPACE}}.shukeyun.com
    http:
      paths:
      - path: /{{PROJECT_NAMESPACE}}/{{PROJECT_NAME}}/?(.*)
        pathType: Prefix
        backend:
          service:
            name: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}-svc    
            port: 
              number: 8080
