---

apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}-svc
  labels:
    name: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}-svc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: {{PROJECT_NAMESPACE}}-{{PROJECT_NAME}}
